get_merged_module_3_data <- function(project) {
  ### Join the Participants table to Merged Module 1 Data
  parts <-
    glue(
      "SELECT Connect_ID, token, d_512820379, d_471593703, ",
      "state_d_934298480, d_230663853, d_335767902,",
      "d_982402227, d_919254129, d_699625233, d_564964481, ",
      "d_795827569, d_544150384, d_371067537, d_430551721, ",
      "d_821247024, d_914594314, d_827220437, d_949302066, ",
      "d_517311251, d_205553981, d_117249500, ",
      "d_976570371, ", # Baseline Survey Status- Module Smoking, Alcohol, and Sun Exposure
      "d_770257102, ", # Autogenerated date/time stamp for Completion of Module Smoking, Alcohol, and Sun Exposure
      "d_663265240, ", # Baseline Survey Status- Module Where You Live and Work
      "d_264644252, ", # Autogenerated date/time stamp for Completion of Module Where You Live and Work
      "FROM `{project}.FlatConnect.participants_JP` ",
      "WHERE Connect_ID IS NOT NULL AND d_831041022='104430631'"
    )
  parts_table <- bq_project_query(project, parts)
  parts_data <- bq_table_download(parts_table,
                                  bigint = "integer64")
  
  mod3 <- glue(
    "SELECT * FROM `{project}.FlatConnect.module3_v1_JP` ",
    "WHERE Connect_ID IS NOT NULL"
  )
  mod3_table <- bq_project_query(project, mod3)
  mod3_data <- bq_table_download(mod3_table,
                                 bigint = "integer64")
  
  merged <- left_join(mod3_data, parts_data, by = "Connect_ID")
  merged
}

# # Test
# project <- "nih-nci-dceg-connect-prod-6d04"
# df_mod3 <- get_merged_module_3_data(project)
