get_merged_module_4_data <- function(project) {
  ### Join the Participants table to Merged Module 1 Data
  parts <-
    glue::glue(
      "SELECT Connect_ID, token, d_512820379, d_471593703, ",
      "state_d_934298480, d_230663853, d_335767902,",
      "d_982402227, d_919254129, d_699625233, d_564964481, ",
      "d_795827569, d_544150384, d_371067537, d_430551721, ",
      "d_821247024, d_914594314, d_827220437, d_949302066, ",
      "d_517311251, d_205553981, d_117249500, ",
      "d_205553981, ", # time stamp for start of Mod1
      "d_541836531, ", # time stamp for start of Mod2
      "d_386488297, ", # time stamp for start of Mod3
      "d_452942800, ", # time stamp for start of Mod 4
      "d_976570371, ", # Baseline Survey Status- Module Smoking, Alcohol, and Sun Exposure
      "d_770257102, ", # Autogenerated date/time stamp for Completion of Module Smoking, Alcohol, and Sun Exposure
      "d_663265240, ", # Baseline Survey Status- Module Where You Live and Work
      "d_264644252, ", # Autogenerated date/time stamp for Completion of Module Where You Live and Work
      "FROM `{project}.FlatConnect.participants_JP` ",
      "WHERE Connect_ID IS NOT NULL AND d_831041022='104430631'"
    )
  parts_table <- bigrquery::bq_project_query(project, parts)
  parts_data <- bigrquery::bq_table_download(parts_table,
                                  bigint = "integer64")
  
  mod4 <- glue::glue(
    "SELECT * FROM `{project}.FlatConnect.module4_v1_JP` ",
    "WHERE Connect_ID IS NOT NULL"
  )
  mod4_table <- bigrquery::bq_project_query(project, mod4)
  mod4_data <- bigrquery::bq_table_download(mod4_table,
                                 bigint = "integer64")
  
  merged_mod4_parts_data <- dplyr::left_join(mod4_data, parts_data, by = "Connect_ID")
  
  mod1_vars <- c("Connect_ID", "D_784967158")
  
  source("get_merged_module_1_data.R")
  mod_1_data <- get_merged_module_1_data(project, specified_m1_vars = mod1_vars, merge_participants_table=FALSE) %>%
    mutate_all(as.character)
  mod_1_data[,'version'] <- NULL
  #mod_1_data$Connect_ID <- as.character(mod_1_data$Connect_ID)
  merged <- dplyr::left_join(merged_mod4_parts_data, mod_1_data, by = "Connect_ID")
  
  return(merged)
}

# Test
project <- "nih-nci-dceg-connect-prod-6d04"
df_mod4 <- get_merged_module_4_data(project)
