default:
  tier: stg
  project_id: "nih-nci-dceg-connect-stg-5519"
  project_number: "810867956467"
  write_to_gcs: TRUE
  bucket: gs://qaqc_reports
  box_app: NCI_BOX_GCP_CONNECT4CANCER_DEV
  box_folder: "211501237681"
  flag: ""
biospecimen:
  QC_REPORT: biospecimen
  rules_file: qc_rules_biospecimen.xlsx
  flag: export2box
recruitment:
  QC_REPORT: recruitment
  rules_file: qc_rules_recruitment.xlsx
module1:
  QC_REPORT: module1
  rules_file: qc_rules_module1.xlsx
  flag: export2box
module2:
  QC_REPORT: module2
  rules_file: qc_rules_module2.xlsx
  flag: export2box
module3:
  QC_REPORT: module3
  rules_file: qc_rules_module3.xlsx
  flag: "export2box"
module4:
  QC_REPORT: module4
  rules_file: qc_rules_module4.xlsx
  flag: "export2box"